export const requiredFields = [
  "merchantId",
  "merchantName",
  "contactTitle",
  "contactName",
  "mobilePhone",
  "email",
  "emailAlerts",
  "physicalAddr",
  "stateCode",
  "terminalModelCode",
  "terminalId",
  "terminalOwnerCode",
  "payAttitudeBin",
  "bankCode",
  "bankAccNo",
  "bankType",
  "accountName",
  "businessOccupationCode",
  "merchantCategoryCode",
  "transactionCurrency",
  "ptsa",
  "ptsp",
  "visaAcquirerIdNumber",
  "verveAcquirerIdNumber",
  "mastercardAcquirerIdNumber",
  "stampDuty",
] as const;

export const tabGroups = {
  company: [
    "merchantId",
    "merchantName",
    "contactTitle",
    "contactName",
    "mobilePhone",
    "email",
    "emailAlerts",
    "physicalAddr",
    "stateCode",
  ],
  terminal: [
    "terminalModelCode",
    "terminalId",
    "terminalOwnerCode",
    "payAttitudeBin",
  ],
  bank: ["bankCode", "bankAccNo", "bankType", "accountName"],
  business: [
    "businessOccupationCode",
    "merchantCategoryCode",
    "transactionCurrency",
    "ptsa",
    "ptsp",
    "visaAcquirerIdNumber",
    "verveAcquirerIdNumber",
    "mastercardAcquirerIdNumber",
    "stampDuty",
  ],
} as const;
